### ISSUE TITLE
Issue with CircleCI Integration

### ISSUE THREAD

**Issue by olizilla** [saucelabs/docs#221]
The examples in github have been updated but the examples in the docs haven't:
https://github.com/circleci/sauce-connect/blob/master/circle.yml

The `circle.yml` example for the **Running** section should show:

```yaml
test:
  override:
    - cd sc-*-linux && ./bin/sc --user $SAUCE_USERNAME --api-key $SAUCE_ACCESS_KEY --readyfile ~/sauce_is_ready:
        background: true
    # Wait for tunnel to be ready
    - while [ ! -e ~/sauce_is_ready ]; do sleep 1; done
```

https://github.com/circleci/sauce-connect/blob/master/circle.yml#L8

The example in the docs do not work currently.

Also of note,
 
```sh
wget https://saucelabs.com/downloads/sc-latest-linux.tar.gz
```

isn't returning the current latest build, but:

```sh
ubuntu@box276:~/medialist-app/sc-4.3-linux$ ./bin/sc 
08 Sep 13:54:59 - Sauce Connect 4.3, build 1283 399e76d
08 Sep 13:54:59 - Using CA certificate bundle /etc/ssl/certs/ca-certificates.crt.
08 Sep 13:54:59 - Using no proxy for connecting to Sauce Labs REST API.
08 Sep 13:55:00 - **********************************************************
08 Sep 13:55:00 - A newer version of Sauce Connect (build 1757) is available!
08 Sep 13:55:00 - Download it here:
08 Sep 13:55:00 - https://saucelabs.com/downloads/sc-4.3.11-linux.tar.gz
08 Sep 13:55:00 - **********************************************************
```
